### ISSUE TITLE
question about special mode while pushing buttons and powering on  the mfj tuner 

### ISSUE THREAD

**Issue by satfan52** [dl9sec/MFJ-993WWRC#1]
Hello,
Nice project, first tests show positive results, very clear instructions too - Thanks !!

I see nothing on the diagram that allows the ES8266 to power on / off the MFJ-993, so how can these special mode be implemented ? Is the user supposed to power on/off  the MFJ-993 by disconnecting the 12V supply via the bias tee ? and at the same time click on the buttons of the UI ?  Why not having the ESP8266 module also control the power supply of the tuner with a power FET or a relay ? This way the 12V would be fed permanently via the bias tee and the ESP would be able to also control the power/on off of the MFJ-993, I just don't understand why it could not be done this way as it would have avoided the battery, the charger and the step-up converter, just another FET or relay to control the power supply to the MFJ-993. Thanks

**Comment by dl9sec** [comment]
Hi,

yes, you are right, the special mode is implemented (just to keep it simple) switching the bias-T and clicking on the UI.

Due to the limited I/Os of the D1 i didn't implement a supply switch. Another reason was, that I didn't want to pull to much critical wires out of the tuner. The bias-T supply of the tuner is at the opposite corner of the tuner where the remote control is plugged. I didn't want to spend too much time to harden the pulled out supply wires against RF.
I assumed that the special function are used very seldom, so the I decided to do it this way.

I am sure it could be done the way you suggested. Feel free to fork and modify the project. I would really appreciate if you could share your efforts too.

Currently I am working on a small M5 Stack based client for the remote control to avoid using the browser UI, so there is no spare time at the moment for me to do modifications you suggested. Looking forward to your progress...

**Comment by satfan52** [comment]
Thank you for your reply. I am also an engineer, but not one like you :) I will try to make the modification in the sketch myself,  it should not be too hard (after all its just an Arduino). I am actually more afraid of what it involves to create the extra power on/off button on the UI, any high level guideline on the development environment to set up for that purpose would be most welcomed. Actually like you, my ultimate plan is get rid of the UI all-together and move  the control pcb (ie, the pcb with the 1602 display and all the buttons)  outside the cabinet using a second ESP8266 so it connects wirelessly to the first esp8266 in the mfj-993 cabinet, maybe using ESPnow instead of a webserver. I would be curious to know your opinion on the technical feasibility of this approach :) I have no idea what the M5 brings to the party in this context but if I understand you correctly, it is essentially the same idea that I have in mind with two ESP8266 and ESPnow. Thanks

**Comment by dl9sec** [comment]
Sorry for replying late...
There should be no need to remove the UI/webserver. It is very easy to request the JSON data from the server and send button commands. If you are interested, I can send you the code of my M5 Stack client (it was ready to use in my tinkerbox and has a display and buttons, nothing more :-) ), it is straight forward and you should be able to modify it for your purpose very easy. My first thought was also to use simple LEDs and some tactile buttons, but I was too lazy to put it all together and put it into a housing...

Maybe I will publish the M5 Stack client within the next few days

**Comment by satfan52** [comment]
Hello again,

Yes that code would be useful to me: 
Please send it to me at on7yi.pik973@gmail.com or publish it on github
Thanks
